import { useCallback, useEffect, useRef, useState } from 'react'
import { useMotionValueEvent } from 'framer-motion'

import sequences from '@/data/sequences.json'
import { useImageSequence } from '@/hooks/useImageSequence'

// Phones (and data-saver mode) get the lighter frame set. Decided once, so resizing doesn't reload.
function pickVariant() {
  const saveData = navigator.connection?.saveData
  return saveData || window.matchMedia('(max-width: 767px)').matches ? 'mobile' : 'desktop'
}

/**
 * Draws an image sequence (generated by scripts/make-sequence.py) onto a canvas,
 * showing the frame that matches `progress` (a 0–1 MotionValue, e.g. scroll progress).
 * Frames start downloading once `enabled` is true. The image is scaled to cover the canvas.
 */
export function useSequenceCanvas({ name, progress, enabled }) {
  const canvasRef = useRef(null)
  const [variant] = useState(pickVariant)
  const { count } = sequences[name][variant]
  const urlFor = useCallback(
    (i) => `/sequence/${name}/${variant}/${String(i + 1).padStart(3, '0')}.webp`,
    [name, variant]
  )

  const [hasFrame, setHasFrame] = useState(false)
  const currentRef = useRef(0)
  const drawnRef = useRef(-1)
  const rafRef = useRef(0)
  const drawRef = useRef(() => {})

  // Redraws are batched to one per animation frame and happen outside React.
  const requestDraw = useCallback(() => {
    if (rafRef.current) return
    rafRef.current = requestAnimationFrame(() => {
      rafRef.current = 0
      drawRef.current()
    })
  }, [])

  const { framesRef, loaded } = useImageSequence({ count, urlFor, enabled, onFrame: requestDraw })

  drawRef.current = () => {
    const canvas = canvasRef.current
    const frames = framesRef.current
    if (!canvas || !frames.length) return
    // Draw the wanted frame, or the closest one that has loaded so far.
    const target = currentRef.current
    let index = -1
    for (let d = 0; d < count && index === -1; d++) {
      if (frames[target - d]) index = target - d
      else if (frames[target + d]) index = target + d
    }
    if (index === -1 || index === drawnRef.current) return

    const img = frames[index]
    const ctx = canvas.getContext('2d')
    const scale = Math.max(canvas.width / img.naturalWidth, canvas.height / img.naturalHeight)
    const w = img.naturalWidth * scale
    const h = img.naturalHeight * scale
    ctx.drawImage(img, (canvas.width - w) / 2, (canvas.height - h) / 2, w, h)
    drawnRef.current = index
    if (!hasFrame) setHasFrame(true)
  }

  // Keep the canvas bitmap matched to its on-screen size (resizing clears it, so redraw).
  useEffect(() => {
    const canvas = canvasRef.current
    const observer = new ResizeObserver(([entry]) => {
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      canvas.width = Math.round(entry.contentRect.width * dpr)
      canvas.height = Math.round(entry.contentRect.height * dpr)
      drawnRef.current = -1
      requestDraw()
    })
    observer.observe(canvas)
    return () => {
      observer.disconnect()
      cancelAnimationFrame(rafRef.current)
      rafRef.current = 0
    }
  }, [requestDraw])

  const syncFrame = useCallback(
    (p) => {
      const frame = Math.min(count - 1, Math.max(0, Math.round(p * (count - 1))))
      if (frame !== currentRef.current) {
        currentRef.current = frame
        requestDraw()
      }
    },
    [count, requestDraw]
  )
  useMotionValueEvent(progress, 'change', syncFrame)
  // Pick up the starting position too (e.g. after a refresh halfway down the page).
  useEffect(() => syncFrame(progress.get()), [progress, syncFrame])

  return { canvasRef, count, loaded, hasFrame }
}
